config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'magic#index', as: 'home'
  get '/new', to: 'magic#new', as: 'new_question'
  post '/', to: 'magic#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/magic_ball_answer.rb
class MagicBallAnswer < ApplicationRecord
  validates :question,
            presence: true

  before_create :answer!
  
  private
  
  def answer!
    answers =
      [
        'it is certain',
        'It is decidedly so',
        'Without a doubt',
        'Yes — definitely',
        'You may rely on it',
        'As I see it, yes',
        'Most likely',
        'Outlook good',
        'Signs point to yes',
        'Yes',
        'Reply hazy, try again',
        'Ask again later',
        'Better not tell you now',
        'Cannot predict now',
        'Concentrate and ask again',
        'Don’t count on it',
        'My reply is no',
        'My sources say no',
        'Outlook not so good',
        'Very doubtful'
      ]
    self.answer = answers[rand(answers.size)]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/magic_controller.rb
class MagicController < ApplicationController
  def index
    @magic_ball_answers =
      MagicBallAnswer.
      order(created_at: :desc).
      limit(10)
  end
  
  def new
    @magic_ball_answer = MagicBallAnswer.new
  end
  
  def create
    @magic_ball_answer = MagicBallAnswer.new(answer_params)

    if @magic_ball_answer.save
      redirect_to home_path
    else
      render :new
    end
  end
  
  private
  
  def answer_params
    params.require(:magic_ball_answer).permit(:question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/magic/index.html.erb
<h1>Last 10 questions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
    </tr>
  </thead>
  <tbody>
    <% @magic_ball_answers.each do |result| %>
      <td><%= result.question %></td>
      <td><%= result.answer %></td>
    <% end %>
  </tbody>
</table>

<%= link_to 'New question', new_question_path %>

app/views/magic/new.html.erb
<%= simple_form_for @magic_ball_answer, url: home_path do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :question %>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>